### ISSUE TITLE
Correções no visual mobile do site

### ISSUE THREAD

**Issue by eminetto** [eminetto/eltonminetto.net#5]
Ao adicionar o novo tema do site, o [Lowkey](https://github.com/nixentric/Lowkey-Hugo-Theme) o visual do site ficou de difícil leitura no mobile pois o espaçamento nas laterais da tela ficaram muito próximo da borda, conforme é possível ver nas imagens a seguir:

---
Home no iPhone
---

![IMG_1739](https://github.com/eminetto/eltonminetto.net/assets/197939/211e04f8-fcfd-4cba-a07a-436765217136 )

---
Página interna no iPhone
---

![IMG_1740](https://github.com/eminetto/eltonminetto.net/assets/197939/a453df47-6826-44bb-a061-44d37defd66f)

---
Home no iPad
---

![IMG_4B62A5913568-1](https://github.com/eminetto/eltonminetto.net/assets/197939/6a286fa0-eb05-4810-bcc4-4ddf2392d624)

---
No desktop o visual está como o esperado:

---
Home no desktop
---

<img width="1271" alt="Captura de Tela 2024-01-14 às 13 01 00" src="https://github.com/eminetto/eltonminetto.net/assets/197939/397dcebb-3ae9-424e-bb4e-98d9567cfce6">

---
Página interna no desktop
---

<img width="1269" alt="Captura de Tela 2024-01-14 às 13 01 10" src="https://github.com/eminetto/eltonminetto.net/assets/197939/2cda9b6b-1019-4f5b-941c-565193251074">

---

É preciso ajustar o CSS para dar mais espaço nas laterais, para ficar mais fácil a leitura do texto.

O site foi construído usando o [Hugo](https://gohugo.io/) e os arquivos do tema estão [neste diretório](https://github.com/eminetto/eltonminetto.net/tree/master/themes/lowkey)

**Comment by juniorsantos** [comment]
Correção feita:

https://github.com/eminetto/eltonminetto.net/pull/6


![image](https://github.com/eminetto/eltonminetto.net/assets/2080742/d084e688-b6da-48fd-813e-fae353a94541)
